const chat=document.getElementById('chat');
const form=document.getElementById('form');
const input=document.getElementById('input');
const quick=document.querySelector('.quick');
const sendLead=document.getElementById('sendLead');
const voiceToggle=document.getElementById('voiceToggle');
const params=new URLSearchParams(location.search);
const contexto={origem:params.get('origem')||'standvirtual',viatura:params.get('viatura')||'',link_anuncio:params.get('link_anuncio')||params.get('url')||params.get('anuncio')||''};
let voiceOn=false;
let history=[];
let lead={nome:'',telefone:'',viatura:contexto.viatura||'',orcamento:'',financiamento:'',retoma:'',horario:'',observacoes:''};
let pendingCars=[],customLeadMode=false,awaitingCustomRequest=false,quickLeadMode=false,quickSelected=[],quickSummaryEl=null,quickQuestionEl=null,detailQueue=[],detailDone={},detailAnswers={},awaitingDetail='';
const OPT={disponibilidade:{label:'disponibilidade',ask:'Quer apenas confirmar a disponibilidade ou pretende avançar para reserva da viatura?'},financiamento:{label:'financiamento',ask:'Que entrada inicial está a pensar dar e qual seria a prestação mensal confortável?'},retoma:{label:'retoma',ask:'Qual é a viatura que tem para retoma? Indique marca, modelo, ano e quilómetros, se souber.'},visita:{label:'marcação de visita/test-drive',ask:'Que dia e hora teria disponibilidade para visita ou test-drive?'}};
const BRAND_LOGOS=[
  {key:'tesla',label:'Tesla',short:'T',rx:/\btesla\b/i},
  {key:'dacia',label:'Dacia',short:'DACIA',rx:/\bdacia\b/i},
  {key:'mg',label:'MG',short:'MG',rx:/\bmg\b|\bmg4\b|\bmgs5\b/i},
  {key:'renault',label:'Renault',short:'R',rx:/\brenault\b/i},
  {key:'hyundai',label:'Hyundai',short:'H',rx:/\bhyundai\b|\bkauai\b/i},
  {key:'nissan',label:'Nissan',short:'N',rx:/\bnissan\b/i},
  {key:'fiat',label:'Fiat',short:'FIAT',rx:/\bfiat\b/i},
  {key:'mercedes',label:'Mercedes-Benz',short:'MB',rx:/\bmercedes\b|\bbenz\b/i},
  {key:'bmw',label:'BMW',short:'BMW',rx:/\bbmw\b/i},
  {key:'volkswagen',label:'Volkswagen',short:'VW',rx:/\bvolkswagen\b|\bvw\b/i}
];
function esc(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function speak(t){try{if(!voiceOn||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(t||'').replace(/https?:\/\/\S+/g,'link').replace(/\s+/g,' ').trim());u.lang='pt-PT';u.rate=.96;window.speechSynthesis.speak(u)}catch(e){}}
function mark(el){document.querySelectorAll('.bot.latest').forEach(x=>x.classList.remove('latest'));if(el&&el.classList.contains('bot'))el.classList.add('latest')}
function add(t,c){const d=document.createElement('div');d.className='msg '+c;d.innerHTML=esc(t);chat.appendChild(d);if(c==='bot'){mark(d);speak(t)}chat.scrollTop=chat.scrollHeight;return d}
function setMsg(el,t){if(!el)return;el.innerHTML=esc(t);if(el.classList.contains('bot')){mark(el);speak(t)}chat.scrollTop=chat.scrollHeight}
function filled(v){return String(v||'').trim()}
function canSend(){return !!(lead.nome&&lead.telefone&&lead.viatura&&(lead.financiamento||lead.retoma||lead.horario||lead.orcamento||lead.observacoes))}
function leadText(){const lines=['Nova lead - Assistente IA'];if(filled(lead.viatura))lines.push('Viatura/Pedido: '+lead.viatura);if(filled(lead.financiamento))lines.push('Financiamento: '+lead.financiamento);if(filled(lead.orcamento))lines.push('Entrada/Prestação: '+lead.orcamento);if(filled(lead.retoma))lines.push('Retoma: '+lead.retoma);if(filled(lead.horario))lines.push('Horário/Visita: '+lead.horario);if(filled(lead.observacoes))lines.push('Observações: '+lead.observacoes);if(filled(lead.nome))lines.push('Cliente: '+lead.nome);if(filled(lead.telefone))lines.push('Contacto: '+lead.telefone);if(filled(contexto.link_anuncio))lines.push('Link: '+contexto.link_anuncio);return lines.join('\n')}
function wa(){return 'https://wa.me/351918404101?text='+encodeURIComponent(leadText())}
function updateSend(){if(canSend()){sendLead.href=wa();sendLead.classList.remove('hidden')}else sendLead.classList.add('hidden')}
function updateQuick(){lead.viatura&&!customLeadMode?quick.classList.remove('hidden'):quick.classList.add('hidden')}
function joinList(a){return a.length<2?(a[0]||''):a.length===2?a[0]+' e '+a[1]:a.slice(0,-1).join(', ')+' e '+a[a.length-1]}
function firstMissingDetail(){return detailQueue.find(k=>quickSelected.includes(k)&&!detailDone[k]&&!filled(detailAnswers[k]))||quickSelected.find(k=>!detailDone[k]&&!filled(detailAnswers[k]))||''}
function rebuild(){lead.financiamento=quickSelected.includes('financiamento')?'Pretende financiamento':'';lead.orcamento=quickSelected.includes('financiamento')&&detailAnswers.financiamento?'Entrada/prestação pretendida: '+detailAnswers.financiamento:'';lead.retoma=quickSelected.includes('retoma')?(detailAnswers.retoma||''):'';lead.horario=quickSelected.includes('visita')&&detailAnswers.visita?'Visita/test-drive: '+detailAnswers.visita:'';let obs=[];if(quickSelected.includes('disponibilidade'))obs.push(detailAnswers.disponibilidade?'Disponibilidade/reserva: '+detailAnswers.disponibilidade:'Cliente pretende confirmar disponibilidade/reserva');if(quickSelected.includes('visita')&&!detailAnswers.visita)obs.push('Cliente pretende marcar visita/test-drive');lead.observacoes=obs.join('; ');updateSend()}
function summary(){if(!quickSelected.length)return 'Nenhuma opção selecionada. Pode escolher uma ou mais opções abaixo.';return 'Perfeito. Fica registado o pedido de '+joinList(quickSelected.map(k=>OPT[k].label))+' para '+lead.viatura+'.'}
function refresh(){rebuild();if(!quickSummaryEl)quickSummaryEl=add(summary(),'bot');else setMsg(quickSummaryEl,summary());askNext(true)}
function askNext(force=false){if(awaitingDetail&&!force)return;if(!quickSelected.length){awaitingDetail='';if(quickQuestionEl)setMsg(quickQuestionEl,'Pode escolher uma ou mais opções abaixo ou escrever diretamente a sua mensagem.');return}const next=firstMissingDetail();if(next){awaitingDetail=next;const total=quickSelected.length,done=quickSelected.filter(k=>detailDone[k]).length+1;const text=done+'/'+total+' — '+OPT[next].label.charAt(0).toUpperCase()+OPT[next].label.slice(1)+': '+OPT[next].ask;if(!quickQuestionEl)quickQuestionEl=add(text,'bot');else setMsg(quickQuestionEl,text);input.focus();return}awaitingDetail='contact';const text='Obrigado. Indique por favor o seu nome e contacto/WhatsApp para enviar o pedido ao Carlos.';if(!quickQuestionEl)quickQuestionEl=add(text,'bot');else setMsg(quickQuestionEl,text);input.focus()}
function toggleQuick(btn){if(!lead.viatura){add('Primeiro escolha a viatura do stock.','bot');return}const k=btn.dataset.key,txt=btn.dataset.label||btn.textContent.replace(/^✓\s*/,'');btn.dataset.label=txt;if(quickSelected.includes(k)){quickSelected=quickSelected.filter(x=>x!==k);detailQueue=detailQueue.filter(x=>x!==k);delete detailDone[k];delete detailAnswers[k];btn.classList.remove('selected');btn.textContent=txt;if(awaitingDetail===k)awaitingDetail=''}else{delete detailDone[k];delete detailAnswers[k];quickSelected.push(k);if(!detailQueue.includes(k))detailQueue.push(k);btn.classList.add('selected');btn.textContent='✓ '+txt}quickLeadMode=quickSelected.length>0;refresh()}
function processQuick(t){if(awaitingDetail&&awaitingDetail!=='contact'){const k=awaitingDetail;detailAnswers[k]=filled(t);detailDone[k]=true;awaitingDetail='';rebuild();askNext(true);return}const missing=firstMissingDetail();if(missing){awaitingDetail=missing;processQuick(t);return}processContact(t)}
function addActions(){const w=document.createElement('div');w.className='inline-actions';const y=document.createElement('button');y.className='send-wa';y.textContent='Sim, enviar ao Carlos';y.onclick=()=>{sendLead.href=wa();sendLead.click()};const n=document.createElement('button');n.textContent='Quero acrescentar algo';n.onclick=()=>add('Claro. Escreva o que pretende acrescentar.','bot');w.append(y,n);chat.appendChild(w);chat.scrollTop=chat.scrollHeight}
function resetQuick(){quickLeadMode=false;quickSelected=[];quickSummaryEl=null;quickQuestionEl=null;detailQueue=[];detailDone={};detailAnswers={};awaitingDetail='';document.querySelectorAll('.quick button').forEach(b=>{b.classList.remove('selected');b.textContent=b.dataset.label||b.textContent.replace(/^✓\s*/,'')})}
function brandFromTitle(title){return BRAND_LOGOS.find(b=>b.rx.test(String(title||'')))||null}
function brandLogoHtml(title){const b=brandFromTitle(title);if(!b)return '<span class="brand-logo-wrap"><span class="brand-logo-fallback visible">AUTO</span></span>';return '<span class="brand-logo-wrap"><img class="brand-logo-img" src="./logos/'+b.key+'.svg" alt="'+b.label+'" loading="lazy" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'inline-flex\'"><span class="brand-logo-fallback">'+b.short+'</span></span>'}
function carOptionHtml(item,i){return brandLogoHtml(item.title)+'<span class="car-title">'+esc((i+1)+'. '+item.title)+'</span>'}
function confirmCar(item){pendingCars=[];customLeadMode=false;resetQuick();contexto.viatura=item.title;contexto.link_anuncio=item.url;lead={nome:'',telefone:'',viatura:item.title,orcamento:'',financiamento:'',retoma:'',horario:'',observacoes:''};updateQuick();updateSend();add('Escolhi: '+item.title,'me');add('Perfeito. Pode escolher uma ou mais opções abaixo — disponibilidade, financiamento, retoma ou marcar visita — ou escrever diretamente a sua mensagem.','bot')}
function addCarOptions(items){pendingCars=items;const w=document.createElement('div');w.className='car-options';items.forEach((it,i)=>{const b=document.createElement('button');b.innerHTML=carOptionHtml(it,i);b.onclick=()=>confirmCar(it);w.appendChild(b);if(it.url){const a=document.createElement('a');a.href=it.url;a.target='_blank';a.rel='noopener';a.textContent='Ver detalhes do anúncio';w.appendChild(a)}});const o=document.createElement('button');o.innerHTML='<span class="brand-logo-wrap"><span class="brand-logo-fallback visible">?</span></span><span class="car-title">Não é nenhum destes, procurar outra viatura</span>';o.onclick=()=>{pendingCars=[];awaitingCustomRequest=true;add('Sem problema. Escreva a viatura pretendida ou deixe uma observação. Também posso enviar esse pedido ao Carlos.','bot')};w.appendChild(o);chat.appendChild(w);chat.scrollTop=chat.scrollHeight}
function registerCustomLead(t){const p=filled(t).slice(0,280);if(!p)return;customLeadMode=true;awaitingCustomRequest=false;contexto.viatura='Pedido fora do stock atual';contexto.link_anuncio='';lead.viatura=p;lead.observacoes='Pedido não encontrado na lista atual de stock.';updateQuick();updateSend();let f=p.replace(/^(sim|s|ok|olá|ola|bom dia|boa tarde|boa noite)[,\s-]+/i,'').trim();if(/^preciso\b/i.test(f))f=f.replace(/^preciso\b/i,'precisa');else if(/^procuro\b/i.test(f))f=f.replace(/^procuro\b/i,'procura');else if(/^quero\b/i.test(f))f=f.replace(/^quero\b/i,'quer');else if(/^pretendo\b/i.test(f))f=f.replace(/^pretendo\b/i,'pretende');else f='procura '+f.charAt(0).toLowerCase()+f.slice(1);add('Compreendo, '+f.replace(/[.?!]*$/,'')+'. Vou enviar esse pedido ao Carlos.','bot');add('Indique por favor o seu nome e contacto/WhatsApp. Se quiser, diga também o melhor horário para contacto.','bot')}
function phone(t){const m=String(t||'').match(/(?:\+?351\s*)?9\d{2}[\s.\-]*\d{3}[\s.\-]*\d{3}/);return m?m[0].replace(/\D/g,'').replace(/^351/,''):''}
function noPhone(t){return String(t||'').replace(/(?:\+?351\s*)?9\d{2}[\s.\-]*\d{3}[\s.\-]*\d{3}/,'').trim()}
function processContact(t){const ph=phone(t),rest=noPhone(t);if(ph&&!lead.telefone)lead.telefone=ph;if(rest&&!lead.nome&&!/^(sim|s|ok|enviar|envia|pode enviar)$/i.test(rest))lead.nome=rest.slice(0,80);updateSend();if(!lead.nome&&lead.telefone){add('Obrigado. Indique por favor o seu nome para enviar o pedido ao Carlos.','bot');return}if(lead.nome&&!lead.telefone){add('Obrigado, '+lead.nome+'. Indique por favor o seu contacto/WhatsApp para o Carlos poder responder.','bot');return}if(lead.nome&&lead.telefone){add('Obrigado, '+lead.nome+'. Já tenho todos os dados essenciais. Pode enviar a lead compilada ao Carlos no botão verde em baixo.','bot');addActions();updateSend();return}add('Indique por favor o seu nome e contacto/WhatsApp para enviar o pedido ao Carlos.','bot')}
function num(t){const n=Number(String(t||'').trim());return Number.isInteger(n)&&n>=1&&n<=pendingCars.length?n:0}
async function loadStock(){try{const r=await fetch('/api/stock'),d=await r.json(),res=Array.isArray(d.results)?d.results:[];if(res.length){add('Estas são as viaturas que encontrei no stock atual. Escolha uma delas para avançar:','bot');addCarOptions(res);setTimeout(()=>chat.scrollTop=0,80);return}}catch(e){}add('Não consegui carregar a lista de stock neste momento. Pode escrever a marca, modelo ou colar o link do anúncio.','bot')}
async function searchStock(q){add('Vou procurar no stock por: '+q,'bot');try{const r=await fetch('/api/stock?q='+encodeURIComponent(q)),d=await r.json(),res=Array.isArray(d.results)?d.results:[];if(res.length===1){add('Encontrei esta viatura no stock:\n'+res[0].title+'\n\nÉ esta a viatura que pretende?','bot');const w=document.createElement('div');w.className='inline-actions';const y=document.createElement('button');y.className='yes-car';y.textContent='Sim, é esta';y.onclick=()=>confirmCar(res[0]);const n=document.createElement('button');n.textContent='Não, procurar outra';n.onclick=()=>{awaitingCustomRequest=true;add('Sem problema. Escreva a viatura pretendida ou deixe uma observação.','bot')};w.append(y,n);chat.appendChild(w);return}if(res.length>1){add('Encontrei estas viaturas no stock:\n'+res.map((it,i)=>(i+1)+'. '+it.title).join('\n')+'\n\nQual delas pretende?','bot');addCarOptions(res);return}registerCustomLead(q)}catch(e){registerCustomLead(q)}}
async function send(t){if(!filled(t))return;const selected=num(t);if(!lead.viatura&&selected){confirmCar(pendingCars[selected-1]);input.value='';return}if(!lead.viatura){add(t,'me');input.value='';if(awaitingCustomRequest){registerCustomLead(t);return}await searchStock(t);return}if(customLeadMode){add(t,'me');input.value='';processContact(t);return}if(quickLeadMode){add(t,'me');input.value='';processQuick(t);return}add(t,'me');history.push({role:'user',content:t});input.value='';input.disabled=true;add('A analisar...','bot');const loading=chat.lastChild;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,history,contexto,lead})}),d=await r.json();loading.remove();if(d.lead)Object.keys(lead).forEach(k=>{if(d.lead[k])lead[k]=String(d.lead[k]).trim().slice(0,280)});const rep=d.reply||d.error||'Não consegui responder agora. Pode contactar diretamente o Carlos pelo WhatsApp 918404101.';add(rep,'bot');history.push({role:'assistant',content:rep});updateSend()}catch(e){loading.remove();add('Não consegui ligar à IA neste momento. Pode enviar o pedido diretamente pelo WhatsApp.','bot')}input.disabled=false;input.focus()}
voiceToggle.onclick=()=>{voiceOn=!voiceOn;voiceToggle.classList.toggle('on',voiceOn);voiceToggle.textContent=voiceOn?'🔊 Voz ligada':'🔇 Voz desligada';if(voiceOn)speak('Voz ligada.')};
form.onsubmit=e=>{e.preventDefault();send(input.value)};
document.querySelectorAll('.quick button').forEach(b=>{b.dataset.label=b.textContent;b.onclick=()=>toggleQuick(b)});
sendLead.onclick=()=>{sendLead.href=wa();add('Vou enviar o pedido para o Carlos.','me')};
if(contexto.viatura){add('Viatura de interesse: '+contexto.viatura+'\nComo posso ajudar em relação a esta viatura?','bot')}else{add('Consultei o stock atual.','bot');loadStock()}
updateQuick();updateSend();