const chat=document.getElementById('chat');
const form=document.getElementById('form');
const input=document.getElementById('input');
const quick=document.querySelector('.quick');
const quickContinue=document.getElementById('quickContinue');
const sendLead=document.getElementById('sendLead');
const welcomeScreen=document.getElementById('welcomeScreen');
const assistantScreen=document.getElementById('assistantScreen');
const startAssistant=document.getElementById('startAssistant');
const showWriter=document.getElementById('showWriter');
const assistantTitle=document.getElementById('assistantTitle');
const assistantSubtitle=document.getElementById('assistantSubtitle');
const params=new URLSearchParams(location.search);
const contexto={origem:params.get('origem')||'standvirtual',viatura:params.get('viatura')||'',link_anuncio:params.get('link_anuncio')||params.get('url')||params.get('anuncio')||''};
const INITIAL_GREETING='Olá! 👋 Vamos encontrar a viatura certa para ti.';
let history=[];
let lead={nome:'',telefone:'',viatura:contexto.viatura||'',orcamento:'',financiamento:'',retoma:'',horario:'',observacoes:''};
let pendingCars=[],customLeadMode=false,awaitingCustomRequest=false,quickLeadMode=false,quickSelected=[],quickSelectionConfirmed=false,combinedDetails='',awaitingDetail='',started=false;
const OPT={disponibilidade:{label:'disponibilidade',ask:'Quer apenas confirmar a disponibilidade ou pretende avançar para reserva da viatura?'},financiamento:{label:'financiamento',ask:'Que entrada inicial está a pensar dar e qual seria a prestação mensal confortável?'},retoma:{label:'retoma',ask:'Qual é a viatura que tem para retoma? Indique marca, modelo, ano e quilómetros, se souber.'},visita:{label:'marcação de visita',ask:'Que dia e hora teria disponibilidade para visitar o stand?'}};
const BRAND_LOGOS=[
  {key:'tesla',label:'Tesla',short:'T',rx:/\btesla\b/i},
  {key:'dacia',label:'Dacia',short:'DACIA',rx:/\bdacia\b/i},
  {key:'mg',label:'MG',short:'MG',rx:/\bmg\b|\bmg4\b|\bmgs5\b/i},
  {key:'renault',label:'Renault',short:'R',rx:/\brenault\b/i},
  {key:'hyundai',label:'Hyundai',short:'H',rx:/\bhyundai\b|\bkauai\b/i},
  {key:'nissan',label:'Nissan',short:'N',rx:/\bnissan\b/i},
  {key:'fiat',label:'Fiat',short:'FIAT',rx:/\bfiat\b/i},
  {key:'mercedes',label:'Mercedes-Benz',short:'MB',rx:/\bmercedes\b|\bbenz\b/i},
  {key:'bmw',label:'BMW',short:'BMW',rx:/\bbmw\b/i},
  {key:'volkswagen',label:'Volkswagen',short:'VW',rx:/\bvolkswagen\b|\bvw\b/i}
];
function esc(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function mark(el){document.querySelectorAll('.bot.latest').forEach(x=>x.classList.remove('latest'));if(el&&el.classList.contains('bot'))el.classList.add('latest')}
function readBot(t,o={}){if(typeof window.queueAssistantSpeech==='function')window.queueAssistantSpeech(t,o)}
function add(t,c,o={}){const d=document.createElement('div');d.className='msg '+c;d.innerHTML=esc(t);chat.appendChild(d);if(c==='bot'){mark(d);if(!o.silent)readBot(t)}chat.scrollTop=chat.scrollHeight;return d}
function setMsg(el,t,o={}){if(!el)return;const changed=el.textContent!==String(t||'');el.innerHTML=esc(t);if(el.classList.contains('bot')){mark(el);if(changed&&!o.silent)readBot(t,o)}chat.scrollTop=chat.scrollHeight}
function filled(v){return String(v||'').trim()}
function canSend(){return !!(lead.viatura&&lead.nome&&lead.telefone&&(lead.financiamento||lead.retoma||lead.horario||lead.orcamento||lead.observacoes))}
function leadText(){const lines=['Nova lead - Assistente IA'];if(filled(lead.viatura))lines.push('Viatura/Pedido: '+lead.viatura);if(quickSelected.length)lines.push('Opções selecionadas: '+joinList(quickSelected.map(k=>OPT[k].label)));if(filled(lead.financiamento))lines.push('Financiamento: '+lead.financiamento);if(filled(lead.orcamento))lines.push('Entrada/Prestação: '+lead.orcamento);if(filled(lead.retoma))lines.push('Retoma: '+lead.retoma);if(filled(lead.horario))lines.push('Horário/Visita: '+lead.horario);if(filled(lead.observacoes))lines.push('Observações: '+lead.observacoes);if(filled(lead.nome))lines.push('Cliente: '+lead.nome);if(filled(lead.telefone))lines.push('Contacto: '+lead.telefone);if(filled(contexto.link_anuncio))lines.push('Link: '+contexto.link_anuncio);return lines.join('\n')}
function wa(){return 'https://wa.me/351918404101?text='+encodeURIComponent(leadText())}
function updateSend(){if(canSend()){sendLead.href=wa();sendLead.classList.remove('hidden')}else sendLead.classList.add('hidden')}
function updateQuick(){lead.viatura&&!customLeadMode?quick.classList.remove('hidden'):quick.classList.add('hidden')}
function placeQuickInChat(){chat.appendChild(quick);updateQuick();chat.scrollTop=chat.scrollHeight}
function joinList(a){return a.length<2?(a[0]||''):a.length===2?a[0]+' e '+a[1]:a.slice(0,-1).join(', ')+' e '+a[a.length-1]}
function rebuild(){lead.financiamento=quickSelected.includes('financiamento')?'Pretende financiamento':'';lead.orcamento='';lead.retoma='';lead.horario='';let obs=[];if(quickSelected.includes('disponibilidade'))obs.push('Cliente pretende confirmar disponibilidade/reserva');if(quickSelected.includes('retoma'))obs.push('Cliente pretende tratar de retoma');if(quickSelected.includes('visita'))obs.push('Cliente pretende marcar visita');if(combinedDetails)obs.push('Resposta conjunta às opções selecionadas: '+combinedDetails);lead.observacoes=obs.join('; ');updateSend()}
function setInputPrompt(label=''){input.classList.toggle('answer-needed',!!label);input.placeholder=label?'Escreva aqui: '+label+'…':'Escreva a sua mensagem...'}
function showComposer(label=''){form.classList.remove('hidden');showWriter.classList.add('hidden');setInputPrompt(label);requestAnimationFrame(()=>{input.focus();input.scrollIntoView?.({block:'nearest'});chat.scrollTop=chat.scrollHeight})}
function hideComposer(){form.classList.add('hidden');showWriter.classList.remove('hidden');setInputPrompt()}
function setStage(title,subtitle){if(assistantTitle)assistantTitle.textContent=title;if(assistantSubtitle)assistantSubtitle.textContent=subtitle}
function updateQuickContinue(){if(!quickContinue)return;const count=quickSelected.length;quickContinue.classList.toggle('hidden',!count||quickSelectionConfirmed);quickContinue.textContent=count===1?'Continuar com esta opção →':'Continuar com '+count+' opções →'}
function combinedQuestion(){const lines=['Perfeito. Responda numa única mensagem:'];if(quickSelected.includes('disponibilidade'))lines.push('• Disponibilidade: pretende apenas confirmar ou avançar para reserva?');if(quickSelected.includes('financiamento'))lines.push('• Financiamento: qual a entrada inicial e a prestação mensal pretendida?');if(quickSelected.includes('retoma'))lines.push('• Retoma: indique marca, modelo, ano e quilómetros da sua viatura.');if(quickSelected.includes('visita'))lines.push('• Marcar visita: indique o dia e a hora preferidos.');lines.push('• Contacto: indique o seu nome e número de telemóvel ou WhatsApp.');return lines.join('\n')}
function confirmQuickSelection(){if(!quickSelected.length||quickSelectionConfirmed)return;quickSelectionConfirmed=true;awaitingDetail='combined';updateQuickContinue();document.querySelectorAll('.quick button[data-key]').forEach(b=>b.disabled=true);setStage('Só faltam alguns dados','Pode responder tudo numa única mensagem.');add(combinedQuestion(),'bot');showComposer('resposta e contacto')}
function toggleQuick(btn){if(!lead.viatura){add('Primeiro escolha a viatura do stock.','bot');return}if(quickSelectionConfirmed)return;const k=btn.dataset.key,txt=btn.dataset.label||btn.textContent.replace(/^✓\s*/,'');btn.dataset.label=txt;if(quickSelected.includes(k)){quickSelected=quickSelected.filter(x=>x!==k);btn.classList.remove('selected');btn.setAttribute('aria-pressed','false');btn.textContent=txt}else{quickSelected.push(k);btn.classList.add('selected');btn.setAttribute('aria-pressed','true');btn.textContent='✓ '+txt}quickLeadMode=quickSelected.length>0;rebuild();updateQuickContinue()}
function explicitName(t){const text=String(t||''),labelled=text.match(/(?:^|\n)\s*(?:nome|cliente)\s*:\s*([^\n,;]{2,80})/i);if(labelled)return labelled[1].trim();const contact=phoneMatch(text);if(!contact)return '';const before=text.slice(0,contact.index).trim();const natural=before.match(/(?:^|[\d€.,;:])\s*(?:(?:km|kms|quilómetros?|quilometros?|euros?|por\s+m[eê]s)\s*)?([A-ZÁÀÂÃÉÊÍÓÔÕÚÇ][A-Za-zÀ-ÿ'’\-]*(?:\s+[A-ZÁÀÂÃÉÊÍÓÔÕÚÇ][A-Za-zÀ-ÿ'’\-]*){0,2})\s*$/);return natural?natural[1].trim():''}
function processQuick(t){if(!quickSelectionConfirmed){quickSelectionConfirmed=true;document.querySelectorAll('.quick button[data-key]').forEach(b=>b.disabled=true);updateQuickContinue()}if(awaitingDetail==='combined'||!combinedDetails){combinedDetails=filled(t).slice(0,700);const ph=phone(t),name=explicitName(t);if(ph)lead.telefone=ph;if(name)lead.nome=name;awaitingDetail='contact';rebuild();if(!lead.nome||!lead.telefone){const missing=!lead.nome&&!lead.telefone?'nome e contacto/WhatsApp':!lead.nome?'nome':'contacto/WhatsApp';add('Obrigado. Falta apenas indicar o seu '+missing+' para enviar o pedido ao Carlos.','bot');showComposer(missing);return}hideComposer();setStage('Pedido pronto','Pode enviá-lo diretamente ao Carlos.');add('Obrigado, '+lead.nome+'. Já tenho todos os dados essenciais. Pode enviar o pedido ao Carlos no botão verde em baixo.','bot');addActions();updateSend();return}processContact(t)}
function addActions(){const w=document.createElement('div');w.className='inline-actions';const y=document.createElement('button');y.className='send-wa';y.textContent='Sim, enviar ao Carlos';y.onclick=()=>{sendLead.href=wa();sendLead.click()};const n=document.createElement('button');n.textContent='Quero acrescentar algo';n.onclick=()=>{add('Claro. Escreva o que pretende acrescentar.','bot');showComposer('mensagem adicional')};w.append(y,n);chat.appendChild(w);chat.scrollTop=chat.scrollHeight}
function resetQuick(){quickLeadMode=false;quickSelected=[];quickSelectionConfirmed=false;combinedDetails='';awaitingDetail='';setInputPrompt();document.querySelectorAll('.quick button[data-key]').forEach(b=>{b.disabled=false;b.classList.remove('selected');b.setAttribute('aria-pressed','false');b.textContent=b.dataset.label||b.textContent.replace(/^✓\s*/,'')});updateQuickContinue()}
function brandFromTitle(title){return BRAND_LOGOS.find(b=>b.rx.test(String(title||'')))||null}
function brandLogoHtml(title){const b=brandFromTitle(title);if(!b)return '<span class="brand-logo-wrap"><span class="brand-logo-fallback visible">AUTO</span></span>';return '<span class="brand-logo-wrap"><img class="brand-logo-img" src="./logos/'+b.key+'.svg" alt="'+b.label+'" loading="lazy" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'inline-flex\'"><span class="brand-logo-fallback">'+b.short+'</span></span>'}
function carOptionHtml(item,i){return '<span class="car-number" aria-hidden="true">'+(i+1)+'</span>'+brandLogoHtml(item.title)+'<span class="car-copy"><span class="car-title">'+esc(item.title)+'</span><span class="car-select">Selecionar viatura <span aria-hidden="true">→</span></span></span>'}
function lockCarOptionsUntilSpeech(w,announcement){w.classList.add('stock-locked');w.setAttribute('aria-busy','true');const controls=[...w.querySelectorAll('.car-choice,.car-details,.car-other')];controls.forEach(el=>{if(el.tagName==='BUTTON')el.disabled=true;else{el.tabIndex=-1;el.setAttribute('aria-disabled','true')}});const gate=document.createElement('button');gate.type='button';gate.className='stock-gate';gate.innerHTML='<span class="stock-gate-icon" aria-hidden="true">🔊</span><strong class="stock-gate-title">A iniciar…</strong><small>Aguarde pela breve apresentação.</small>';w.appendChild(gate);let released=false;const release=()=>{if(released)return;released=true;window.removeEventListener('assistant-speech-state',onSpeech);w.classList.remove('stock-locked');w.removeAttribute('aria-busy');controls.forEach(el=>{if(el.tagName==='BUTTON')el.disabled=false;else{el.removeAttribute('tabindex');el.removeAttribute('aria-disabled')}});gate.remove()};const onSpeech=event=>{const detail=event.detail||{};if(detail.state==='finished'&&detail.text===announcement)release();if(['failed','off','unavailable'].includes(detail.state))release()};window.addEventListener('assistant-speech-state',onSpeech);if(window.lastAssistantSpeech===announcement||['off','unavailable'].includes(window.assistantVoiceState))release()}
function confirmCar(item){pendingCars=[];customLeadMode=false;resetQuick();contexto.viatura=item.title;contexto.link_anuncio=item.url;lead={nome:'',telefone:'',viatura:item.title,orcamento:'',financiamento:'',retoma:'',horario:'',observacoes:''};hideComposer();updateQuick();updateSend();setStage('O que pretende saber?','Pode escolher uma ou várias opções.');add('Escolhi: '+item.title,'me');add('Perfeito. Escolha uma ou mais opções abaixo.','bot');placeQuickInChat()}
function addCarOptions(items,lockAnnouncement=''){pendingCars=items;const w=document.createElement('div');w.className='car-options';const head=document.createElement('div');head.className='stock-list-head';head.innerHTML='<strong>Viaturas disponíveis</strong><span class="stock-count">'+items.length+'</span>';w.appendChild(head);items.forEach((it,i)=>{const card=document.createElement('article');card.className='car-card';if(i>=6)card.classList.add('car-extra','hidden');const b=document.createElement('button');b.className='car-choice';b.type='button';b.setAttribute('aria-label','Selecionar '+it.title);b.innerHTML=carOptionHtml(it,i);b.onclick=()=>confirmCar(it);card.appendChild(b);if(it.url){const a=document.createElement('a');a.className='car-details';a.href=it.url;a.target='_blank';a.rel='noopener';a.setAttribute('aria-label','Abrir anúncio de '+it.title);a.title='Ver anúncio';a.innerHTML='<span aria-hidden="true">↗</span>';card.appendChild(a)}w.appendChild(card)});if(items.length>6){const more=document.createElement('button');more.type='button';more.className='show-more';more.textContent='Mostrar mais '+(items.length-6)+' viaturas';more.onclick=()=>{w.querySelectorAll('.car-extra').forEach(card=>card.classList.remove('hidden'));more.remove();chat.scrollTop=chat.scrollHeight};w.appendChild(more)}const o=document.createElement('button');o.className='car-other';o.type='button';o.innerHTML='<span class="brand-logo-wrap"><span class="brand-logo-fallback visible">?</span></span><span class="car-copy"><span class="car-title">Não encontra a viatura?</span><span class="car-select">Escreva a marca ou modelo <span aria-hidden="true">→</span></span></span>';o.onclick=()=>{pendingCars=[];awaitingCustomRequest=true;setStage('Que viatura procura?','Escreva a marca, o modelo ou cole o anúncio.');add('Sem problema. Escreva a viatura pretendida ou deixe uma observação. Também posso enviar esse pedido ao Carlos.','bot');showComposer('marca ou modelo')};w.appendChild(o);chat.appendChild(w);if(lockAnnouncement)lockCarOptionsUntilSpeech(w,lockAnnouncement);chat.scrollTop=chat.scrollHeight}
function registerCustomLead(t){const p=filled(t).slice(0,280);if(!p)return;customLeadMode=true;awaitingCustomRequest=false;contexto.viatura='Pedido fora do stock atual';contexto.link_anuncio='';lead.viatura=p;lead.observacoes='Pedido não encontrado na lista atual de stock.';updateQuick();updateSend();let f=p.replace(/^(sim|s|ok|olá|ola|bom dia|boa tarde|boa noite)[,\s-]+/i,'').trim();if(/^preciso\b/i.test(f))f=f.replace(/^preciso\b/i,'precisa');else if(/^procuro\b/i.test(f))f=f.replace(/^procuro\b/i,'procura');else if(/^quero\b/i.test(f))f=f.replace(/^quero\b/i,'quer');else if(/^pretendo\b/i.test(f))f=f.replace(/^pretendo\b/i,'pretende');else f='procura '+f.charAt(0).toLowerCase()+f.slice(1);setStage('Só falta o contacto','O Carlos responderá diretamente.');add('Compreendo, '+f.replace(/[.?!]*$/,'')+'. Vou enviar esse pedido ao Carlos.','bot');add('Indique por favor o seu nome e contacto/WhatsApp. Se quiser, diga também o melhor horário para contacto.','bot');showComposer('nome e contacto/WhatsApp')}
function phoneMatch(t){return String(t||'').match(/(?:\+?351\s*)?9\d{1,2}(?:[\s.\-]*\d){6}/)}
function phone(t){const m=phoneMatch(t);return m?m[0].replace(/\D/g,'').replace(/^351/,''):''}
function noPhone(t){const text=String(t||''),m=phoneMatch(text);return m?(text.slice(0,m.index)+text.slice(m.index+m[0].length)).trim():text.trim()}
function processContact(t){const ph=phone(t),rest=noPhone(t);if(ph&&!lead.telefone)lead.telefone=ph;if(rest&&!lead.nome&&!/^(sim|s|ok|enviar|envia|pode enviar)$/i.test(rest))lead.nome=rest.slice(0,80);updateSend();if(!lead.nome&&lead.telefone){add('Obrigado. Indique por favor o seu nome para enviar o pedido ao Carlos.','bot');showComposer('nome');return}if(lead.nome&&!lead.telefone){add('Obrigado, '+lead.nome+'. Indique por favor o seu contacto/WhatsApp para o Carlos poder responder.','bot');showComposer('contacto/WhatsApp');return}if(lead.nome&&lead.telefone){hideComposer();setStage('Pedido pronto','Pode enviá-lo diretamente ao Carlos.');add('Obrigado, '+lead.nome+'. Já tenho todos os dados essenciais. Pode enviar o pedido ao Carlos no botão verde em baixo.','bot');addActions();updateSend();return}add('Indique por favor o seu nome e contacto/WhatsApp para enviar o pedido ao Carlos.','bot');showComposer('nome e contacto/WhatsApp')}
function num(t){const n=Number(String(t||'').trim());return Number.isInteger(n)&&n>=1&&n<=pendingCars.length?n:0}
async function loadStock(){try{const r=await fetch('/api/stock'),d=await r.json(),res=Array.isArray(d.results)?d.results:[];if(res.length){addCarOptions(res);setTimeout(()=>chat.scrollTop=0,80);return}}catch(e){}add('Não consegui carregar a lista de stock neste momento. Pode escrever a marca, o modelo ou colar o link do anúncio.','bot');showComposer('marca ou modelo')}
async function searchStock(q){add('Vou procurar no stock por: '+q,'bot');try{const r=await fetch('/api/stock?q='+encodeURIComponent(q)),d=await r.json(),res=Array.isArray(d.results)?d.results:[];if(res.length===1){add('Encontrei esta viatura no stock:\n'+res[0].title+'\n\nÉ esta a viatura que pretende?','bot');const w=document.createElement('div');w.className='inline-actions';const y=document.createElement('button');y.className='yes-car';y.textContent='Sim, é esta';y.onclick=()=>confirmCar(res[0]);const n=document.createElement('button');n.textContent='Não, procurar outra';n.onclick=()=>{awaitingCustomRequest=true;add('Sem problema. Escreva a viatura pretendida ou deixe uma observação.','bot');showComposer('marca ou modelo')};w.append(y,n);chat.appendChild(w);return}if(res.length>1){add('Encontrei estas viaturas no stock. Escolha uma delas:','bot');addCarOptions(res);hideComposer();return}registerCustomLead(q)}catch(e){registerCustomLead(q)}}
async function send(t){if(!filled(t))return;const selected=num(t);if(!lead.viatura&&selected){confirmCar(pendingCars[selected-1]);input.value='';return}if(!lead.viatura){add(t,'me');input.value='';if(awaitingCustomRequest){registerCustomLead(t);return}await searchStock(t);return}if(customLeadMode){add(t,'me');input.value='';processContact(t);return}if(quickLeadMode){add(t,'me');input.value='';processQuick(t);return}add(t,'me');history.push({role:'user',content:t});input.value='';input.disabled=true;add('A analisar...','bot',{silent:true});const loading=chat.lastChild;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,history,contexto,lead})}),d=await r.json();if(!r.ok)throw new Error('assistant-unavailable');loading.remove();if(d.lead)Object.keys(lead).forEach(k=>{if(d.lead[k])lead[k]=String(d.lead[k]).trim().slice(0,280)});const rep=d.reply||'Não consegui confirmar essa informação automaticamente. Indique o seu nome e contacto/WhatsApp para o Carlos responder.';add(rep,'bot');history.push({role:'assistant',content:rep});updateSend()}catch(e){loading.remove();add('Não consegui confirmar essa informação automaticamente neste momento. Indique o seu nome e contacto/WhatsApp para o Carlos responder.','bot')}input.disabled=false;input.focus()}
function startExperience(){if(started)return;started=true;welcomeScreen.classList.add('hidden');assistantScreen.classList.remove('hidden');if(contexto.viatura){setStage('Como podemos ajudar?','Escolha uma ou várias opções.');add('Olá! 👋 Vi que estás interessado nesta viatura: '+contexto.viatura+'\nComo posso ajudar?','bot');hideComposer();placeQuickInChat()}else{setStage('Escolha uma viatura','Toque numa viatura para continuar.');add(INITIAL_GREETING,'bot');hideComposer();loadStock()}requestAnimationFrame(()=>{chat.scrollTop=0})}
form.onsubmit=e=>{e.preventDefault();send(input.value)};
document.querySelectorAll('.quick button[data-key]').forEach(b=>{b.dataset.label=b.textContent;b.setAttribute('aria-pressed','false');b.onclick=()=>toggleQuick(b)});
quickContinue.onclick=confirmQuickSelection;
showWriter.onclick=()=>showComposer();
startAssistant.onclick=startExperience;
sendLead.onclick=()=>{sendLead.href=wa();add('Vou enviar o pedido para o Carlos.','me')};
let viewportMax=Math.max(window.innerHeight,window.visualViewport?window.visualViewport.height:0);
function syncViewport(){const vv=window.visualViewport,current=vv?vv.height:window.innerHeight;viewportMax=Math.max(viewportMax,current);const keyboardOpen=viewportMax-current>120;document.documentElement.style.setProperty('--app-height',Math.round(current)+'px');document.body.classList.toggle('keyboard-open',keyboardOpen);if(keyboardOpen)requestAnimationFrame(()=>{chat.scrollTop=chat.scrollHeight})}
if(window.visualViewport){window.visualViewport.addEventListener('resize',syncViewport);window.visualViewport.addEventListener('scroll',syncViewport)}
window.addEventListener('orientationchange',()=>{viewportMax=0;setTimeout(syncViewport,250)});
input.addEventListener('focus',()=>setTimeout(syncViewport,80));
input.addEventListener('blur',()=>setTimeout(syncViewport,120));
if(contexto.viatura)startAssistant.innerHTML='▶&nbsp;&nbsp;Continuar com esta viatura';
syncViewport();
updateQuick();
updateSend();
